### PR TITLE
feat: update tree-sitter-cli version

### PR DESCRIPTION
**Pull request by alexmozaidze**
Updated tree-sitter-cli version to the latest as of writing.

Also, fixed a typo in `locals.scm`.

After this PR gets merged, I will update queries and the parser in nvim-treesitter in order to make programming in Zig more epic.

EDIT: This PR also seems to speed up the parser, at least in Neovim. There are no more notable performance slowdowns like before.

### CODE REVIEW

**Comment by GrayJack** [comment]
In the second commit, it is all autogenerated code?

**Comment by alexmozaidze** [comment]
Yeah. I can rebase and remove the second commit if you want to generate it yourself.

**Comment by GrayJack** [comment]
No need, I was just checking, It's been a while since I last used tree-sitter.

I checked how things are working these days and I can now do a proper review

**Review by GrayJack — APPROVED** [review]
LGTM

**Pull request merged**
